BEGIN;

DROP TABLE "studies";
TRUNCATE TABLE "study_request_comments" RESTART IDENTITY CASCADE;
TRUNCATE TABLE "study_requests" RESTART IDENTITY CASCADE;

ALTER TABLE "study_requests"
  ADD COLUMN "studyType" VARCHAR NOT NULL,
  ADD COLUMN "daysOfWeek" SMALLINT[] NOT NULL,
  ADD COLUMN "duration" SMALLINT DEFAULT NULL,
  ADD COLUMN "hours" VARCHAR DEFAULT NULL,
  ADD COLUMN "notes" VARCHAR NOT NULL;

UPDATE "APP_META"."DB_UPDATE" SET "currentVersion" = 11;
COMMIT;
