import Boom from '@hapi/boom';
import MimeTypes from 'mime-types';

import { HttpStatus } from '@/lib/Constants';
import storageStrategy from '@/lib/io/storage/StorageStrategy';
import Joi from '@/lib/model/Joi';

/**
 * Provides read-only access to MOVE file storage.
 *
 * See {@link StorageStrategyBase} for more details on file storage in MOVE.  In these routes,
 * `namespace` and `key` are used as described there.
 *
 * @type {Array<Hapi.ServerRoute>}
 */
const StorageController = [];

/**
 * Fetch the file at the given `namespace` and `key`.
 *
 * This was originally introduced to allow users to download ZIP archives of
 * reports, as generated by {@link JobController}.
 *
 * Note also that this endpoint does not currently set `Content-Disposition`.  Use `FileSaver`
 * to initiate client-side download of the response body.
 *
 * @memberof StorageController
 * @name getStorage
 * @type {Hapi.ServerRoute}
 */
StorageController.push({
  method: 'GET',
  path: '/storage/{namespace}/{key}',
  options: {
    description: 'Get the stored file at the given namespace / key',
    tags: ['api'],
    validate: {
      params: {
        namespace: Joi.string().required(),
        key: Joi.string().required(),
      },
    },
  },
  handler: async (request, h) => {
    const { namespace, key } = request.params;
    let fileExists;
    try {
      fileExists = await storageStrategy.has(namespace, key);
    } catch (err) {
      const { statusCode } = HttpStatus.BAD_REQUEST;
      return Boom.boomify(err, { statusCode, override: false });
    }
    if (!fileExists) {
      return Boom.notFound(`file not found in storage: ${namespace}/${key}`);
    }

    let mimeType = MimeTypes.lookup(key);
    if (mimeType === false) {
      mimeType = 'application/octet-stream';
    }

    const fileStream = storageStrategy.getStream(namespace, key);
    return h.response(fileStream)
      .type(mimeType);
  },
});

export default StorageController;
