stages:
  - install-app
  - test
  - deploy

install-app:
  stage: install-app
  script:
  - nvm install
  - nvm use
  - npm install

test-build:
  stage: test
  script:
  - npm run docs:build
  - npm run frontend:build

# test-coverage:
#   stage: test
#   script:
#   - npm run test:db-startup
#   - npm run ci:jest-coverage
#   - npm run test:db-shutdown

test-compliance:
  stage: test
  script:
  - npm run ci:npm-audit
  - npm run ci:npm-outdated

deploy:
  stage: deploy
  script:
  - echo deploy
  only:
  - master
