stages:
  - test
  - deploy

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules/

# run coverage tests on every feature branch
test-coverage:
  stage: test
  before_script:
    - nvm install
    - nvm use
    - npm install -g pnpm
    - pnpm install
    - cp -r /home/ec2-user/config-private/* .
  script:
    - npm run test:db-startup
    - npm run ci:jest-coverage
    - npm run test:db-shutdown
  only:
    - /^gh.*-.*$/

# run rest of CI tests on every release branch
test-ci-rest:
  stage: test
  before_script:
    - nvm install
    - nvm use
    - npm install -g pnpm
    - pnpm install
    - cp -r /home/ec2-user/config-private/* .
  script:
    - npm run ci:npm-audit
    - npm run ci:npm-outdated
    - npm run docs:build
    - npm run frontend:build
  only:
    - /^gh.*-version-.*$/

# deploy master to dev automatically
deploy-dev:
  stage: deploy
  script:
    - ./scripts/deployment/code-commit/deploy_code_commit.sh
  only:
    - master

# deploy QA branch automatically
deploy-qa:
  stage: deploy
  script:
    - echo deploy-qa
  only:
    - deploy-qa

# deploy staging automatically
deploy-staging:
  stage: deploy
  script:
    - echo deploy-staging
  only:
    - deploy-staging

# deploy prod manually after approval
deploy-prod:
  stage: deploy
  script:
    - echo deploy-prod
  only:
    - deploy-prod
  when: manual
