stages:
  - test
  - deploy

cache:
  paths:
    - .npm/

before_script:
  - nvm install
  - nvm use
  - npm ci --cache .npm --prefer-offline

test-coverage:
  stage: test
  script:
  - npm run test:db-startup
  - npm run ci:jest-coverage
  - npm run test:db-shutdown

test-build:
  stage: test
  script:
  - npm run docs:build
  - npm run frontend:build
  only:
  - /^.*-version-.*$/

test-compliance:
  stage: test
  script:
  - npm run ci:npm-audit
  - npm run ci:npm-outdated
  only:
  - /^.*-version-.*$/

deploy:
  stage: deploy
  script:
  - echo deploy
  only:
  - master
