stages:
  - test
  - deploy

cache:
  key:
    files:
      - package.json
  paths:
    - node_modules/

# run coverage tests on every feature branch
test-coverage:
  stage: test
  before_script:
    - nvm install
    - nvm use
    - npm ci
    - cp -r /home/ec2-user/config-private/* .
  script:
    - npm run test:db-startup
    - npm run ci:jest-coverage
    - npm run test:db-shutdown
  only:
    - /^gh.*-.*$/

# run rest of CI tests on every release branch
test-ci-rest:
  stage: test
  before_script:
    - nvm install
    - nvm use
    - npm ci
    - cp -r /home/ec2-user/config-private/* .
  script:
    - npm run ci:npm-audit
    - npm run ci:npm-outdated
    - npm run docs:build
    - npm run frontend:build
  only:
    - /^gh.*-version-.*$/

# master -> AWS dev
deploy-dev:
  stage: deploy
  script:
    - ./scripts/deployment/code-commit/deploy_code_commit.sh
  only:
    - master

# deploy-qa -> AWS QA
deploy-qa:
  stage: deploy
  script:
    - ./scripts/deployment/code-commit/deploy_code_commit.sh
  only:
    - deploy-qa

# deploy-prod -> AWS prod
# WARNING: only push here with Change Advisory Board approval
deploy-prod:
  stage: deploy
  script:
    - ./scripts/deployment/code-commit/deploy_code_commit.sh
  only:
    - deploy-prod
