CREATE USER :username WITH NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD ':password';
GRANT CONNECT ON DATABASE flashcrow TO :username;

GRANT USAGE ON SCHEMA "TRAFFIC" TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA "TRAFFIC" TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA "TRAFFIC"
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA collision_factors TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA collision_factors TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA collision_factors
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA collisions TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA collisions TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA collisions
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA counts TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA counts TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA counts
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA gis TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA gis TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA gis
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA location_search TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA location_search TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA location_search
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA open_data TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA open_data TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA open_data
	GRANT SELECT ON TABLES TO :username;

GRANT USAGE ON SCHEMA public TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
	GRANT SELECT ON TABLES TO :username;

GRANT SELECT ON public.geography_columns TO :username;
GRANT SELECT ON public.geometry_columns TO :username;
GRANT SELECT ON public.spatial_ref_sys TO :username;

GRANT USAGE ON SCHEMA volume TO :username;
GRANT SELECT ON ALL TABLES IN SCHEMA volume TO :username;
ALTER DEFAULT PRIVILEGES IN SCHEMA volume
	GRANT SELECT ON TABLES TO :username;
